# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa4a8132bb572008505ded5930bbe01ac74092a3dd24acbff6f5e471a6e7828477360e7865fb3bc3ae9938349ad1d1ce2331590b94033a9ea6aa93fcd2edb1a9

test:
  secret_key_base: 232183f325b8aa4048eb766d3a9a1885c7413a701951395efc06b9deb93f6ccfc1853bced7de25612e58b5751b944ba44910f49aa9bde45f3401344f0607fea3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
