require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ListEntriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ListEntry. As you add validations to ListEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ListEntriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all list_entries as @list_entries" do
      list_entry = ListEntry.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:list_entries)).to eq([list_entry])
    end
  end

  describe "GET #show" do
    it "assigns the requested list_entry as @list_entry" do
      list_entry = ListEntry.create! valid_attributes
      get :show, params: {id: list_entry.to_param}, session: valid_session
      expect(assigns(:list_entry)).to eq(list_entry)
    end
  end

  describe "GET #new" do
    it "assigns a new list_entry as @list_entry" do
      get :new, params: {}, session: valid_session
      expect(assigns(:list_entry)).to be_a_new(ListEntry)
    end
  end

  describe "GET #edit" do
    it "assigns the requested list_entry as @list_entry" do
      list_entry = ListEntry.create! valid_attributes
      get :edit, params: {id: list_entry.to_param}, session: valid_session
      expect(assigns(:list_entry)).to eq(list_entry)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ListEntry" do
        expect {
          post :create, params: {list_entry: valid_attributes}, session: valid_session
        }.to change(ListEntry, :count).by(1)
      end

      it "assigns a newly created list_entry as @list_entry" do
        post :create, params: {list_entry: valid_attributes}, session: valid_session
        expect(assigns(:list_entry)).to be_a(ListEntry)
        expect(assigns(:list_entry)).to be_persisted
      end

      it "redirects to the created list_entry" do
        post :create, params: {list_entry: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ListEntry.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved list_entry as @list_entry" do
        post :create, params: {list_entry: invalid_attributes}, session: valid_session
        expect(assigns(:list_entry)).to be_a_new(ListEntry)
      end

      it "re-renders the 'new' template" do
        post :create, params: {list_entry: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested list_entry" do
        list_entry = ListEntry.create! valid_attributes
        put :update, params: {id: list_entry.to_param, list_entry: new_attributes}, session: valid_session
        list_entry.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested list_entry as @list_entry" do
        list_entry = ListEntry.create! valid_attributes
        put :update, params: {id: list_entry.to_param, list_entry: valid_attributes}, session: valid_session
        expect(assigns(:list_entry)).to eq(list_entry)
      end

      it "redirects to the list_entry" do
        list_entry = ListEntry.create! valid_attributes
        put :update, params: {id: list_entry.to_param, list_entry: valid_attributes}, session: valid_session
        expect(response).to redirect_to(list_entry)
      end
    end

    context "with invalid params" do
      it "assigns the list_entry as @list_entry" do
        list_entry = ListEntry.create! valid_attributes
        put :update, params: {id: list_entry.to_param, list_entry: invalid_attributes}, session: valid_session
        expect(assigns(:list_entry)).to eq(list_entry)
      end

      it "re-renders the 'edit' template" do
        list_entry = ListEntry.create! valid_attributes
        put :update, params: {id: list_entry.to_param, list_entry: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested list_entry" do
      list_entry = ListEntry.create! valid_attributes
      expect {
        delete :destroy, params: {id: list_entry.to_param}, session: valid_session
      }.to change(ListEntry, :count).by(-1)
    end

    it "redirects to the list_entries list" do
      list_entry = ListEntry.create! valid_attributes
      delete :destroy, params: {id: list_entry.to_param}, session: valid_session
      expect(response).to redirect_to(list_entries_url)
    end
  end

end
